# Generated by Django 4.0.4 on 2022-05-14 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_faq_message_settings_profile_images'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Settings',
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='message',
            name='phone',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='news',
            name='type',
            field=models.CharField(choices=[('Haber', 'Haber'), ('Köşe Yazısı', 'Köşe Yazısı')], max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Kullanıcı', 'Kullanıcı'), ('Muhabir', 'Muhabir'), ('Yazar', 'Yazar')], max_length=10),
        ),
    ]
