# Generated by Django 4.0.4 on 2022-05-21 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_contactformmessage_rename_ip_message_ip'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactFormMessage',
        ),
    ]
