# Generated by Django 4.0.4 on 2022-05-25 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_delete_contactformmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='news',
            name='user',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
