# Generated by Django 4.0.4 on 2022-05-14 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('keywords', models.CharField(blank=True, max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('company', models.CharField(blank=True, max_length=150)),
                ('address', models.TextField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=10)),
                ('fax', models.CharField(blank=True, max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('smtpserver', models.URLField(blank=True)),
                ('smtpemail', models.EmailField(blank=True, max_length=254)),
                ('smtppassword', models.CharField(blank=True, max_length=30)),
                ('smtpport', models.IntegerField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('True', 'Evet'), ('False', 'Hayır')], max_length=10)),
            ],
        ),
    ]
