# Generated by Django 4.0.4 on 2022-05-14 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='smtpport',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
