# Generated by Django 4.0.4 on 2022-05-14 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_settings_smtpport'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='icon',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
