# Generated by Django 4.0.4 on 2022-05-21 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_settings_aboutus_settings_contact_settings_create_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='fax',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='settings',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
