# Generated by Django 4.0.4 on 2022-05-25 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(blank=True, choices=[('Kullanıcı', 'Kullanıcı'), ('Muhabir', 'Muhabir'), ('Yazar', 'Yazar')], max_length=10),
        ),
    ]
